apiVersion: v1
kind: ServiceAccount
metadata:
  name: sysdig-account
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sysdig-cluster-role
rules:
  - apiGroups: ["extensions",""]
    resources: ["nodes","namespaces","pods","replicationcontrollers","services","events"]
    verbs: ["get","list","watch"]
  - nonResourceURLs: ["/healthz", "/healthz/*"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sysdig-cluster-role-binding
  namespace: sysdig
subjects:
  - kind: ServiceAccount
    name: sysdig-account
    namespace: sysdig
roleRef:
  kind: ClusterRole
  name: sysdig-cluster-role
  apiGroup: rbac.authorization.k8s.io
